package ntut.csie.backlogItemAttachFileService.useCase.backlogItemAttachFile.get;

import ntut.csie.backlogItemAttachFileService.useCase.UseCase;

public interface GetBacklogItemAttachFilesByBacklogItemIdUseCase extends UseCase<GetBacklogItemAttachFilesByBacklogItemIdInput, GetBacklogItemAttachFilesByBacklogItemIdOutput> {

}
